title: My cooking blog
author: Abinaya
email: anand2@ocdsb.ca
description: > # delicious recipes
Expect new recipes every three days, with a mix of savory and sweet, including desserts, breakfasts, entrées, and more.

# social links
twitter_username: thecook
github_username:  redlotus15

show_excerpts: true # set to false to remove excerpts on the homepage
theme: minima
