title: Chef abinaya
author: abinaya
email: anand2@ocdsb.ca
description: > # this means to ignore newlines until "baseurl:"
 If you don’t have fancy ingredients, expensive equipment, or hours to cook meals every night, you’re in the right place. 

# social links
twitter_username: cookthebest
github_username:  redlotus15

show_excerpts: true # set to false to remove excerpts on the homepage
